base/urls.py
from unicodedata import name
from venv import create
from django.urls import path
from base import views 


urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('register/', views.registerPage, name='register'),
    path('tags/<str:pk>', views.tagPage, name='tag'),
    path('posts/<str:pk>', views.postPage, name='post'),
    path('posts/<str:pk>/edit', views.editPost, name='editPost'),
    path('new-post/', views.createPost, name='newPost'),
    path('users/<str:username>', views.profilePage, name='profile'),
    path('users/<str:username>/edit', views.profileEdit, name='profileEdit'),
]

poster/urls.py
import imp
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL)

api/models.py
from django.db import models

# Create your models here.

base/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField

# Create your models here.
class tag(models.Model):
    name = models.CharField(max_length=300)
    describtion = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.name

class post(models.Model):
    name = models.CharField(max_length=300)
    text = models.TextField()
    auther = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(tag, blank=True, null=True)
    
    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.name 
    
class comment(models.Model):
    text = models.TextField()
    auther = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(post, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.text[0:20]
    
class profile(models.Model):
    genders = [
        ('N', 'Rather not to say'),
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    
    avatar = models.ImageField(null=True, blank=True, upload_to='avatars')
    full_name = models.CharField(max_length=100,null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    gender = models.CharField(max_length=1, default='N', choices=genders)
    country = CountryField(null=True, blank=True)
    related_user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    
    def __str__(self):
        return self.related_user.username

base/forms.py
from xml.parsers.expat import model
from django.forms import ModelForm
from base.models import post, profile

class postForm(ModelForm):
    class Meta:
        model = post
        fields = ['name', 'text', 'tags']

class profileForm(ModelForm):
    class Meta:
        model = profile
        fields = '__all__'

api/views.py
from django.shortcuts import render

# Create your views here.

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from base.models import comment, post, tag, profile
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from base import forms
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
# Create your views here.
def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    latest_posts = post.objects.filter(
        Q(name__icontains=q)|
        Q(auther__username__icontains=q)
    )
    all_tags = tag.objects.all()
    context = {'posts': latest_posts, 'tags':all_tags}
    return render(request, 'home.html', context)

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')
            return redirect('login')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Invalid login or password.')   
            return redirect('login')
        
    return render(request, 'login.html')
        
def registerPage(request):
    form = UserCreationForm()
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            form.save()
            user_profile = profile(related_user=user)
            user_profile.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error happend during registertion :(')
    context = {'form': form}
    return render(request, 'register.html', context)

def logoutPage(request):
    logout(request)
    return redirect('home')

def tagPage(request, pk):
    tag_object = get_object_or_404(tag, id=pk)
    related_posts = tag_object.post_set.all()
    return render(request, 'tag.html', {'tag': tag_object, 'posts': related_posts})

def postPage(request, pk):
    post_object = get_object_or_404(post, id=pk)
    related_comments = comment.objects.filter(post=post_object)
    
    context = {'post':post_object, 'comments': related_comments}
    return render(request, 'post.html', context)

@login_required(login_url='login')
def editPost(request, pk):
    post_object = get_object_or_404(post,id=pk)
    form = forms.postForm(instance=post_object)
    if request.method == 'POST':
        form = forms.postForm(request.POST, instance=post_object)
        if form.is_valid():
            form.save()
            messages.success(request, 'post updated successfully')
        else:
            messages.error(request, 'entries are invalid')
    
    return render(request, 'edit_post.html', {'form': form}) 

@login_required(login_url='login')
def createPost(request):
    form = forms.postForm()
    
    if request.method == 'POST':
        form = forms.postForm(request.POST)
        if form.is_valid():
            post_object = form.save(commit=False)
            post_object.auther = request.user
            post_object.save()
            messages.success(request, 'Post created successfully')
            return redirect('post', pk=post_object.id)
            
    return render(request, 'edit_post.html', {'form': form})

def profilePage(request, username):
    related_user = get_object_or_404(User, username=username)
    profile_object = get_object_or_404(profile, related_user=related_user)
    related_posts = related_user.post_set.all()
    context = {'user': related_user, 'profile': profile_object, 'media': settings.MEDIA_URL, 'posts': related_posts}
    return render(request, 'profile.html', context)

@login_required(login_url='login')
def profileEdit(request, username):
    related_user = get_object_or_404(User, username=username)
    profile_object = get_object_or_404(profile, related_user=related_user)
    form = forms.profileForm(instance=profile_object)
    if request.method == 'POST':
        form = forms.profileForm(request.POST, instance=profile_object)
        if form.is_valid():
            form.save()
    
    return render(request, 'profile_edit.html', {'form': form})

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    </head>
    <body>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
        {% include 'navbar.html' %}
        {% block main %}{% endblock main %}
    </body>
</html>

templates/edit_post.html
{% extends 'base.html' %}

{% block main %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
{% endblock main %}

templates/home.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            sidebar
        </div>
        <div class="col-md-6">
            {% for post in posts %}
            <a href="{% url 'post' post.id %}">
                <div class="card">
                    <div class="card-body">
                      <h5 class="card-title">{{post.name}}</h5>
                      {% for tag in post.tags.all %}
                      <a href="{% url 'tag' tag.id %}"><span class="badge rounded-pill bg-secondary">{{tag.name}}</span></a>
                      {% endfor %}
                      {% if request.user.username == post.auther.username %}
                      <a href="{% url 'editPost' post.id %}">edit</a>
                      {% endif %}
                      <a href="">{{post.auther.username}}</a>
                      <p class="card-text">{{post.text}}</p>
                      <p class="card-text"><small class="text-muted">{{post.created|timesince}} ago</small></p>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
    
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block main %}

<div class="form-signin w-100 m-auto text-center container">
    <form method="POST">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>    
        <div class="form-floating">
          <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Enter your Username...">
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
          <label for="floatingPassword">Password</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
        <p class="mt-5 mb-3 text-muted">Havent Signed Up Yet?</p>
        <a href="{% url 'register' %}">Sign Up</a>
    </form>
</div>

{% endblock main %}

templates/navbar.html
<header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'home' %}" class="nav-link px-2 link-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 link-dark">Explore</a></li>
          {% if request.user.is_authenticated %}
          <li><a href="{% url 'logout' %}" class="nav-link px-2 link-dark">logout</a></li>
          <li><a href="{% url 'register' %}" class="nav-link px-2 link-dark">Sign up</a></li>
          {% else %}
          <li><a href="{% url 'login' %}" class="nav-link px-2 link-dark">login</a></li>
          {% endif %}
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'home' %}">
          <input type="search" name="q" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            {% if request.user.profile_set.all.avatar %}
            <img src="request.user.profile_set.all.avatar" alt="mdo" width="32" height="32" class="rounded-circle">
            {% else %}
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
            {% endif %}
          </a>
          <ul class="dropdown-menu text-small">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">{{request.user}}</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
          </ul>
        </div>
      </div>
    </div>
</header>

templates/post.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <div>
        <h2>{{post.name}}</h2>
        {% for tag in post.tags.all %}
        <a href="{% url 'tag' tag.id %}"><span class="badge rounded-pill bg-secondary">{{tag.name}}</span></a>
        {% endfor %}
    </div>
    <div>
        {{post.text}}
    </div>
    
</div>
{% endblock main %}

templates/profile.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <div class="text-center">
        <div>
            {% if profile.avatar %}
            <img class="rounded-circle mb-3"  style="width: 150px;height: 150px;" src="{{media}}{{profile.avatar.name}}">
            {% else %}
            <img class="rounded-circle mb-3"  style="width: 150px;height: 150px;" src="{{media}}/avatar.png">
            {% endif %}
        </div>
        <div>
            <h3>@{{user.username}}</h3>
        </div>
        <hr>
        <div>
            {% if profile.bio %}
              {{profile.bio}}
            {% endif %}
        </div>
        <div>
            {% for post in posts %}
            <a href="{% url 'post' post.id %}">
                <div class="card">
                    <div class="card-body">
                      <h5 class="card-title">{{post.name}}</h5>
                      {% for tag in post.tags.all %}
                      <a href="{% url 'tag' tag.id %}"><span class="badge rounded-pill bg-secondary">{{tag.name}}</span></a>
                      {% endfor %}
                      {% if request.user.username == post.auther.username %}
                      <a href="{% url 'editPost' post.id %}">edit</a>
                      {% endif %}
                      <a href="">{{post.auther.username}}</a>
                      <p class="card-text">{{post.text}}</p>
                      <p class="card-text"><small class="text-muted">{{post.created|timesince}} ago</small></p>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock main %}

templates/profile_edit.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <div class="text-center">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Save" class="btn btn-info">
        </form>
    </div>
</div>
{% endblock main %}

templates/register.html
{% extends 'base.html' %}

{% block main %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Sign Up" class="btn btn-info">
</form>
{% endblock main %}

templates/tag.html
{% extends 'base.html' %}

{% block main %}
{{tag.name}}
{% for post in posts  %}
{{post}}
{% endfor %}
{% endblock main %}